// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsRmFgA1wk2XY2gaA1MJ5kBAbMuc7BWIA',
    appId: '1:881263223078:web:6a225247f62ffaa0b721e7',
    messagingSenderId: '881263223078',
    projectId: 'wasat-5e536',
    authDomain: 'wasat-5e536.firebaseapp.com',
    storageBucket: 'wasat-5e536.appspot.com',
    measurementId: 'G-5SV29279NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDA_GTIlVk1Vz_cXVWC-C6FDw6VlGsOco',
    appId: '1:881263223078:android:79b39c4b4b540febb721e7',
    messagingSenderId: '881263223078',
    projectId: 'wasat-5e536',
    storageBucket: 'wasat-5e536.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVhSUVtCTFNmfUoh1pGOIIwMBicYYNUbk',
    appId: '1:881263223078:ios:c4b4bd9e29e0ea7cb721e7',
    messagingSenderId: '881263223078',
    projectId: 'wasat-5e536',
    storageBucket: 'wasat-5e536.appspot.com',
    iosBundleId: 'com.example.wasat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVhSUVtCTFNmfUoh1pGOIIwMBicYYNUbk',
    appId: '1:881263223078:ios:b300b555a9f9b93ab721e7',
    messagingSenderId: '881263223078',
    projectId: 'wasat-5e536',
    storageBucket: 'wasat-5e536.appspot.com',
    iosBundleId: 'com.example.wasat.RunnerTests',
  );
}
